//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_RECEIPT_DETAIL
    {
        public int ExportDetailID { get; set; }
        public Nullable<int> ExportID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> VATPercent { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual EXPORT_RECEIPT EXPORT_RECEIPT { get; set; }
    }
}
