//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPORT_RECEIPT()
        {
            this.EXPORT_RECEIPT_DETAIL = new HashSet<EXPORT_RECEIPT_DETAIL>();
        }
    
        public int ExportID { get; set; }
        public string ExportCode { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExporType { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public Nullable<decimal> Shippingfee { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPORT_RECEIPT_DETAIL> EXPORT_RECEIPT_DETAIL { get; set; }
    }
}
