//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORT_RECEIPT()
        {
            this.IMPORT_RECEIPT_DETAIL = new HashSet<IMPORT_RECEIPT_DETAIL>();
        }
    
        public int ImportID { get; set; }
        public string ImportCode { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string SupplierName { get; set; }
        public string Note { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_RECEIPT_DETAIL> IMPORT_RECEIPT_DETAIL { get; set; }
    }
}
