//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_RECEIPT_DETAIL
    {
        public Nullable<int> ImportID { get; set; }
        public Nullable<int> BookID { get; set; }
        public int ImportDetailID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Costprice { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual IMPORT_RECEIPT IMPORT_RECEIPT { get; set; }
    }
}
