//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testBookEntities : DbContext
    {
        public testBookEntities()
            : base("name=testBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<EXPORT_RECEIPT_DETAIL> EXPORT_RECEIPT_DETAIL { get; set; }
        public virtual DbSet<IMPORT_RECEIPT_DETAIL> IMPORT_RECEIPT_DETAIL { get; set; }
        public virtual DbSet<EXPORT_RECEIPT> EXPORT_RECEIPT { get; set; }
        public virtual DbSet<IMPORT_RECEIPT> IMPORT_RECEIPT { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMER_TYPE> CUSTOMER_TYPE { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<SALE> SALEs { get; set; }
        public virtual DbSet<SALE_DETAIL> SALE_DETAIL { get; set; }
    }
}
